version: "3.8"
services:
  server:
    container_name: openfire
    build: .
    ports:
      - "9090:9090"
      - "5222:5222"
  database:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: nick
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: openfiredb
    volumes:
      - "./openfire_mysql.sql:/docker-entrypoint-initdb.d/openfire_mysql.sql"
