version: "3.8"
services:
  server:
    container_name: openfire
    build: .
    ports:
      - "9090:9090"
      - "5222:5222"
  database:
    container_name: mysql_openfire
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: openfire
    ports:
      - "3306:3306"
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"
